version: '3.8'

services:
  backend:
    image: headliner-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    
    ports:
      - "5000:5000"
    env_file: 
      - ./.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always
    depends_on:
      mysql:
        condition: service_healthy


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always


  mysql:
    image: mysql:8.0
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 10
    env_file:
      - ./.env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}